import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { haffer } from "../fonts";
import { getDictionary, Locale } from "@/app/[lang]/dictionaries";
import HomeClient from "@/components/common/home-client";
import Footer from "@/components/common/footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "es" }];
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const dict = await getDictionary(lang as Locale);
  
  return (
    <html
      lang={lang}
      className={cn(
        "h-full",
        "antialiased",
        geistMono.variable,
        haffer.variable,
        "font-haffer",
      )}
    >
      <body className="min-h-full flex flex-col bg-black">
        <TooltipProvider>
          <HomeClient dict={dict} lang={lang} />
          <div className="flex-1 flex flex-col w-full">
            {children}
          </div>
          <Footer dict={dict} lang={lang} />
        </TooltipProvider>
      </body>
    </html>
  );
}
